### ISSUE TITLE
JSON decoding error.

### ISSUE THREAD

**Issue by 3mirhan** [3mirhan/lichess-php#2]
<br />
<font size='1'><table class='xdebug-error xe-catchable-fatal-error' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Catchable fatal error: Object of class stdClass could not be converted to string in C:\wamp64\www\lichess\form.php on line <i>7</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0015</td><td bgcolor='#eeeeec' align='right'>240640</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64\www\lichess\form.php' bgcolor='#eeeeec'>...\form.php<b>:</b>0</td></tr>
</table></font>

**Comment by v0na** [comment]
json decodu dediğim gibi kullanırsanız jsonunuz array'e dönüşür, forumda yazdığım örnekte vardı zaten.

<?php
header("Content-Type: application/json; charset=UTF-8");

$file = file_get_contents("https://lichess.org/api/user/$_POST[isim]");
$array = json_decode($file,true);

print_r($array);
?>

**Comment by v0na** [comment]
```
<?php
header("Content-Type: application/json; charset=UTF-8");

$file = file_get_contents("https://lichess.org/api/user/$_POST[isim]");
$array = json_decode($file,true);

print_r($array);
?>

```

**Comment by 3mirhan** [comment]
çalışıyor, teşekkürler.. Peki `$array = json_decode($file,true);` deki true ne işe yarıyor açıklayabilir misiniz?

**Comment by v0na** [comment]
rica ederim. eğer true kullanırsanız; json_decode array olarak döner. eğer kullanmazsanız object olarak döner.

kısaca;

eğer true kullanırsanız
$var = json_decode($json,true);
echo $var['username'];
şeklinde çağırırsınız.

eğer kullanmazsanız
$var = json_decode($json);
echo $var->username;
şeklinde çağırırsınız

**Comment by 3mirhan** [comment]
peki array içindeki arrayları nasıl çağıracağım. decodelenmiş JSON şöyle güzüküyor.

`

[online] =>
--
  | [perfs] => Array
  | (
  | [blitz] => Array
  | (
  | [games] => 90
  | [rating] => 1298
  | [rd] => 61
  | [prog] => 26
  | )
`

**Comment by v0na** [comment]
echo $array['perfs']['blitz']['rating']
gibi...
